# Generated by Django 6.0.3 on 2026-04-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialrecord',
            old_name='type',
            new_name='record_type',
        ),
    ]
