# Generated by Django 6.0.3 on 2026-04-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_type_financialrecord_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
