# Generated by Django 6.0.3 on 2026-04-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financialrecord_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
