# Generated by Django 6.0.3 on 2026-04-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_financialrecord_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
